// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjvBkqhrleac5Y7uXLBR4LDFy1Jc7yRg8',
    appId: '1:57362494447:web:185d3faf8defe7d553bc1a',
    messagingSenderId: '57362494447',
    projectId: 'proyecto-pmsn-2024',
    authDomain: 'proyecto-pmsn-2024.firebaseapp.com',
    databaseURL: 'https://proyecto-pmsn-2024-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-pmsn-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphfMeG_caDwuJJFlOL3HOY7Tq0ktc-Rw',
    appId: '1:57362494447:android:ad35ee9cf56a1ca453bc1a',
    messagingSenderId: '57362494447',
    projectId: 'proyecto-pmsn-2024',
    databaseURL: 'https://proyecto-pmsn-2024-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-pmsn-2024.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjvBkqhrleac5Y7uXLBR4LDFy1Jc7yRg8',
    appId: '1:57362494447:web:9eae5c652505bef053bc1a',
    messagingSenderId: '57362494447',
    projectId: 'proyecto-pmsn-2024',
    authDomain: 'proyecto-pmsn-2024.firebaseapp.com',
    databaseURL: 'https://proyecto-pmsn-2024-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-pmsn-2024.appspot.com',
  );
}
